# -*- coding: utf-8 -*-
"""monte_carlo_problem2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YxlnQtkDNB1aswqLJURzSIDGX0cKgUEC
"""

import math
import numpy as np
import matplotlib.pyplot as plt

#circle center = (0,0), radius =3
trial_list = [100,1000,5000,10000]
hits = 0

x_hits_list =[]
y_hits_list =[]
x_miss_list =[]
y_miss_list =[]


for n in trial_list:
  print()
  print("For trial n = ", n)

  for i in range(n):
    x = np.random.uniform(0,3)
    y = np.random.uniform(0,8)
    y_point = (2*x +2) 

    if y<= y_point:
      hits +=1
      x_hits_list.append(x)
      y_hits_list.append(y)
    else:
      x_miss_list.append(x)
      y_miss_list.append(y)

      
  print("Hits = ",hits)
  #area_under_line = area of rectengular * (hits / n)
  #area_under_line = (x*y_point) * (hits/n)
  area_under_line = 24 * (hits/n)
  print ("area under line = ",area_under_line)
  print()

  plt.scatter(x_hits_list,y_hits_list,color="red",label="Hit Points")
  plt.scatter(x_miss_list,y_miss_list,color="green",label="Miss Points")
  
  plt.legend()
  plt.show()
  x_hits_list.clear()
  y_hits_list.clear()
  x_miss_list.clear()
  y_miss_list.clear()