# -*- coding: utf-8 -*-
"""monte+carlo_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_S6OWKCC0Fgn2JJEQrnv6nmG2lwAE6B
"""

import math
import numpy as np
import matplotlib.pyplot as plt

trial = [100,1000,5000,10000]
hit = 0
radius = 3
xHit = []
yHit = []
xMiss= []
yMiss= []
Pi_list =[]
circle_list =[]

for n in trial:
  print ("n =",n)
  
  for i in range(n):
    x=np.random.uniform(-5,5)
    y=np.random.uniform(-5,5)

    if (math.sqrt((x**2)+(y**2))) <= radius:
      hit = hit+1
      xHit.append(x)
      yHit.append(y)
    else:
      xMiss.append(x)
      yMiss.append(y)
  Pi_value = (25/(radius**2))* (hit/n)
  Pi_list.append(Pi_value)
  print("Pi Value =",Pi_value)

  circle_area = 25 / (hit/n)
  circle_list.append(circle_area)
  print("Circle Area =",circle_area)
  print()

  plt.scatter(xHit,yHit,color="red",label="Hit")
  plt.scatter(xMiss,yMiss,color="green",label="Miss")
  
  plt.legend()
  plt.show()
  xHit.clear()
  yHit.clear()
  xMiss.clear()
  yMiss.clear()

"""# **First Plot Bar**"""

n=["100","1000","5000","10000"]
print("Pi value list : ",Pi_list)
plt.bar(n,Pi_list, color = "green")
plt.xlabel("Value of n")
plt.ylabel("PI-value")
plt.show()

"""# **Second Plot Bar**"""

n=["100","1000","5000","10000"]
print("Circle Area list : ",circle_list)
plt.bar(n,circle_list, color = "green")
plt.xlabel("Value of n")
plt.ylabel("Circle Area")
plt.show()