# -*- coding: utf-8 -*-
"""monteCarlo_even_task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GShBq-TCinsA3JA4oHy64GLFdzHPwpUV
"""

import math
import numpy as np
import matplotlib.pyplot as plt

trial = [100,1000,5000,10000]
hit = 0
xHit = []
yHit = []
xMiss= []
yMiss= []

for n in trial:
  print ("n =",n)
  
  for i in range(n):
    x=np.random.uniform(0,8)
    y=np.random.uniform(0,4)

    if x<=4:
      if y <= (math.sqrt(4*x)):
        hit =hit+1
        xHit.append(x)
        yHit.append(y)
      else:
        xMiss.append(x)
        yMiss.append(y)
    else:
      if y<= (8-x):
        hit =hit+1
        xHit.append(x)
        yHit.append(y)
      else:
        xMiss.append(x)
        yMiss.append(y)

  area_under_the_curve = 32*(hit/n)
  print("area under the curve =",area_under_the_curve)
  
  plt.scatter(xHit,yHit,color="red",label="Hit")
  plt.scatter(xMiss,yMiss,color="green",label="Miss")
  
  plt.legend()
  plt.show()
  xHit.clear()
  yHit.clear()
  xMiss.clear()
  yMiss.clear()