# -*- coding: utf-8 -*-
"""monte_carlo_problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFHSo2xg667pcuFccxnV9zHshFXgFDOR
"""

import math
import numpy as np
import matplotlib.pyplot as plt

#circle center = (0,0), radius =3
trial_list = [100,1000,5000,10000]
hits = 0
#center
ax = 0
ay = 0
r = 3 #radius
x_hits_list =[]
y_hits_list =[]
x_miss_list =[]
y_miss_list =[]
pi_list =[]
circle_area_list =[]

for n in trial_list:
  print()
  print("For trial n = ", n)



  for i in range(n):
    x = np.random.uniform(-3,3)
    y = np.random.uniform(-5,5)
    
    if math.sqrt (((x-ax)**2)+((y-ay)**2)) <= r:
      hits +=1
      x_hits_list.append(x)
      y_hits_list.append(y)
    else:
      x_miss_list.append(x)
      y_miss_list.append(y)

      
  print("Hits = ",hits)
  Pi = (60/(r**2)) * (hits/n)
  pi_list.append(Pi)
  print ("pi value = ",Pi)
  area_of_circle = 60 * (hits/n)
  circle_area_list.append(area_of_circle)
  print ("area of circle = ",area_of_circle)
  print()

  plt.scatter(x_hits_list,y_hits_list,color="red",label="Hit Points")
  plt.scatter(x_miss_list,y_miss_list,color="green",label="Miss Points")
  
  plt.legend()
  plt.show()
  x_hits_list.clear()
  y_hits_list.clear()
  x_miss_list.clear()
  y_miss_list.clear()
print(pi_list)

"""# ***First bar plot***
x-axis: number of trials, 

y-axis: PI -value (Shown in the class)
"""

print("Pi value list : ",pi_list)
x = np.array(["100","1000","5000","10000"])
y = pi_list
plt.bar(x, y, color = "green",width=0.7)
plt.xlabel("Value of n")
plt.ylabel("PI-value")
plt.show()

"""# ***Second plot Bar***

x-axis: number of trials

y-axis: Area of the circle 
"""

print ("Circle area list : ",circle_area_list)
x = np.array(["100","1000","5000","10000"])
y= circle_area_list
plt.bar(x, circle_area_list, color='green',width=0.7)

#plt.bar(trial_list,pi_list,color='green',width=0.3)

plt.xlabel("Value of n")
plt.ylabel("Area of the circle")
plt.show()