# -*- coding: utf-8 -*-
"""monte_carlo_problem3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mgRuRz16HuSU1Q5fIakU9jAUAZjeBUPB
"""

import math
import numpy as np
import matplotlib.pyplot as plt

trial_list = [100,1000,5000,10000]
hits1=0

x_hits_list1 =[]
y_hits_list1 =[]
x_miss_list1 =[]
y_miss_list1 =[]


for n in trial_list:
  print()
  print("For trial n = ", n)
 # print()

  for i in range(n):
    x = np.random.uniform(0,8)
    y = np.random.uniform(0,4)
     
    if x<=4:
      # equation for curve y^2 = 4x
      y_point_for_curve = math.sqrt(4*x)
      if y<= y_point_for_curve:
        hits1 +=1
        x_hits_list1.append(x)
        y_hits_list1.append(y)
      else:
        x_miss_list1.append(x)
        y_miss_list1.append(y)
    else:
      # equation  y = 8-x
      y_point_for_triangle = 8-x
      if y<= y_point_for_triangle:
        hits1 +=1
        x_hits_list1.append(x)
        y_hits_list1.append(y)
      else:
        x_miss_list1.append(x)
        y_miss_list1.append(y)
  #area  = arae of rectengular  *(hits / trial)
  area_of_curve = 32 * (hits1 / n)
  print ("area of curve = ",area_of_curve)
  print()

  plt.scatter(x_hits_list1,y_hits_list1,color="red",label="Hit Points")
  plt.scatter(x_miss_list1,y_miss_list1,color="green",label="Miss Points")
  
  plt.legend()
  plt.show()
  x_hits_list1.clear()
  y_hits_list1.clear()
  x_miss_list1.clear()
  y_miss_list1.clear()