# -*- coding: utf-8 -*-
"""monte_carlo_integral_0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vPEW3Wi_J5TToNWPWGcTwVFRqK9QykN8
"""

import math
import random
import matplotlib.pyplot as plt

#equation f(x) = x * e^x  limit 0 to 5
trial = [100,500,1000,5000]
a=0
b=5
error_list =[]
for n in trial:
  print ("For n =",n)
  func_sum = 0
  func_square_sum = 0
  for i in range (n):
    x= random.uniform(0,5)
    func= x*(math.exp(x))
    c= func
    func_sum += c

    function_square = c**2
    func_square_sum += function_square

  func_avg = func_sum / n
  func_square_avg = func_square_sum/n

  intregal= func_avg *(b-a)
  print ("Intregal =",intregal)
  error = ((b-a)/ math.sqrt(n)) * math.sqrt(func_square_avg -(func_avg**2)) 
  error_list.append(error)
  print("Error =",error)
  print()

print()
print("Error list : ",error_list)
print ()
x = ["100","500","1000","5000"]
y = error_list
plt.bar(x, y, color = "green",width=0.7)
plt.xlabel("Value of n")
plt.ylabel("Error value")
plt.show()