# -*- coding: utf-8 -*-
"""monteCarlo_even_task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12c9F5w092uvj5cmdrFTkuUVBwTaE7dNB
"""

import math
import numpy as np
import matplotlib.pyplot as plt

trial = [100,1000,5000,10000]
hit = 0
xHit = []
yHit = []
xMiss= []
yMiss= []

for n in trial:
  print ("n =",n)
  
  for i in range(n):
    x=np.random.uniform(0,3)
    y=np.random.uniform(0,5)

    if y<=(x+2):
      hit = hit+1
      xHit.append(x)
      yHit.append(y)
    else:
      xMiss.append(x)
      yMiss.append(y)
  area_of_triangle = 15*(hit/n)
  print("area of triangle =",area_of_triangle)
  print()

  plt.scatter(xHit,yHit,color="red",label="Hit")
  plt.scatter(xMiss,yMiss,color="green",label="Miss")
  
  plt.legend()
  plt.show()
  xHit.clear()
  yHit.clear()
  xMiss.clear()
  yMiss.clear()