# -*- coding: utf-8 -*-
"""monte_carlo_integral_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10TvQFryGuzy2rR8lPXke06JritXQqRkS
"""

import math
import numpy as np
import matplotlib.pyplot as plt

# equation y^2 = 4x (limit 0 to 4) and y=8-x (limit 4 to 8)

trial_list = [100,1000,5000,10000] 

integral_error_list =[]

for n in trial_list:
  print()
  print("For trial n = ", n)

  func_sum_circle = 0
  func_square_sum_circle = 0
  func_sum_line = 0
  func_square_sum_line = 0

  for i in range(n):
    x = np.random.uniform(0,4)
    # equation y^2 = 4x
    func_circle =math.sqrt(4*x) 
    func_sum_circle +=func_circle
    b= (func_circle)**2
    func_square_sum_circle += b
  
  func_sum_circle_avg = func_sum_circle / n
  func_square_sum_circle_avg = func_square_sum_circle /n
  intregal_for_equation_circle = func_sum_circle_avg  *(4-0)
  
  error_circle = ((4-0)/ math.sqrt(n)) * math.sqrt(func_square_sum_circle_avg -(func_sum_circle_avg**2)) 

  for j in range(n):
    x = np.random.uniform(4,8)
    # equation  y = 8-x
    func_line = 8-x
    func_sum_line +=func_line

    d= (func_line)**2
    func_square_sum_line += d
  func_sum_line_avg = func_sum_line / n
  func_square_sum_line_avg = func_square_sum_line /n
  intregal_for_equation_line = func_sum_line_avg  *(8-4)

  error_line = ((8-4)/ math.sqrt(n)) * math.sqrt(func_square_sum_line_avg -(func_sum_line_avg**2)) 

  total_integral = intregal_for_equation_circle + intregal_for_equation_line
  print("Total Area = ",total_integral)
  
  final_error =(error_circle + error_line) /2
  integral_error_list.append(final_error)
  print("Error =",final_error)
  print()

print()
print("Error list : ",integral_error_list)
print ()
x = ["100","1000","5000","10000"]
y = integral_error_list
plt.bar(x, y, color = "green",width=0.7)
plt.xlabel("Value of n")
plt.ylabel("Error value")
plt.show()